[package]
name = "host"
version = "0.1.0"
authors = ["Discookie <matekos17@fazekas.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "host"
path = "./src/lib.rs"

[dependencies]
actix-web = "1.0"
